data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"
  synthetic_n: 5000
  random_seed: 42

model:
  test_size: 0.20
  cv_folds: 5

co2:
  kwh_per_gb: 0.000849
  carbon_tr: 0.475
  pue: 1.58

unsplash:
  client_id: "TMJn3JBWklV193o204pZCfVX2P5wgN9EmniLexz35Xw"
  n_photos: 30